# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adela Neacsu
author: Created by Adela Neacsu. 
email: adella.neacsu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nqryn
github_username:  nqryn
linkedin_username: adela-neacsu-76aaa456
youtube_username: AdelaNeacsu
googleplus_username: +AdelaNeacsu
stackoverflow_userid: 3231146

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# This allows you to set which pages you want to appear in the navigation area and configure order of the links.
header_pages:
  - about.md
  - portfolio.md
  - contact.md
  - research.md

# Enable comments on posts (using Disqus)
disqus:
  shortname: adelaneacsu-eu

# Enabling Excerpts from Posts on the Home Page
show_excerpts: true